#!/bin/bash
# ------------------------------------------------------------------------------
# $Id$
# ------------------------------------------------------------------------------

cd jmvc

echo '*************************************************************************'
echo Checking if fixtures are disabled
echo '*************************************************************************'

cat seccubus/seccubus.js | perl -e 'while (<>) { if ( /fixtures\.js/ && ! /^\s*\/[\/\*]/ ) { print $_; } }'|tee /tmp/test.$$;

if [ `cat /tmp/test.$$|wc -l` -ne 0 ]
then
	echo "Disable fixtures first";
	rm /tmp/test.$$
	exit 1
fi
echo No fixtures found
rm /tmp/test.$$

echo '*************************************************************************'
echo Building JMVC package
echo '*************************************************************************'
./js seccubus/scripts/build.js 2>&1|tee /tmp/test.$$
if [ `grep -i error /tmp/test.$$|grep -v error.ejs|wc -l` -ne 0 ]
then
	echo "Not building any further, fix your errors first"
	mv /tmp/test.$$ ../errors.txt
	less ../errors.txt
	exit 1
fi
echo "Package built"
rm /tmp/test.$$

echo '*************************************************************************'
echo Copying files
echo '*************************************************************************'
cd ..
rm -rf www/seccubus/*
cp -r jmvc/seccubus/img www/seccubus
cp jmvc/seccubus/production.* www/seccubus
cp jmvc/seccubus/seccubus.html www/seccubus
rm -rf www/steal/*
cp jmvc/steal/steal.production.js www/steal

echo '*************************************************************************'
echo Patching files
echo '*************************************************************************'
mv www/seccubus/seccubus.html www/seccubus/seccubus.html.bak
sed s:steal\.js:steal.production.js: www/seccubus/seccubus.html.bak >www/seccubus/seccubus.html
(cd www/seccubus/;ln -s ../json)
echo end
