#!/bin/bash
# ------------------------------------------------------------------------------
# $Id$
# ------------------------------------------------------------------------------
#  Copyright 2011 Frank Breedijk of Schuberg Philis
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# ------------------------------------------------------------------------------
cd jmvc

echo '*************************************************************************'
echo Checking if fixtures are disabled
echo '*************************************************************************'

cat seccubus/seccubus.js | perl -e 'while (<>) { if ( /fixtures\.js/ && ! /^\s*\/[\/\*]/ ) { print $_; } }'|tee /tmp/test.$$;

if [ `cat /tmp/test.$$|wc -l` -ne 0 ]
then
	echo "Disable fixtures first";
	rm /tmp/test.$$
	exit 1
fi
echo No fixtures found

echo '*************************************************************************'
echo Building JMVC docs
echo '*************************************************************************'
./js seccubus/scripts/docs.js

echo '*************************************************************************'
echo Building JMVC package
echo '*************************************************************************'
./js seccubus/scripts/build.js 2>&1|tee /tmp/test.$$
if [ `grep -i error /tmp/test.$$|wc -l` -ne 0 ]
then
	echo "Not building any further, fix your errors first"
	mv /tmp/test.$$ ../errors.txt
	less ../errors.txt
	exit 1
fi
echo "Package built"

echo '*************************************************************************'
echo Copying files
echo '*************************************************************************'
cd ..
rm -rf www/seccubus/*
cp -r jmvc/seccubus/img www/seccubus
cp jmvc/seccubus/production.* www/seccubus
cp jmvc/seccubus/seccubus.html www/seccubus
rm -rf www/steal/*
cp jmvc/steal/steal.production.js www/steal

echo '*************************************************************************'
echo Patching files
echo '*************************************************************************'
mv www/seccubus/seccubus.html www/seccubus/seccubus.html.bak
sed s:steal\.js:steal.production.js: www/seccubus/seccubus.html.bak >www/seccubus/seccubus.html
(cd www/seccubus/;ln -s ../json)
echo end
