#!/bin/bash
# Copyright 2011-2017 Frank Breedijk
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

cd jmvc

echo '*************************************************************************'
echo Checking if fixtures are disabled
echo '*************************************************************************'

cat seccubus/seccubus.js | perl -e 'while (<>) { if ( /fixtures\.js/ && ! /^\s*\/[\/\*]/ ) { print $_; } }'|tee /tmp/test.$$;

if [ `cat /tmp/test.$$|wc -l` -ne 0 ]
then
	echo "Disable fixtures first";
	rm /tmp/test.$$
	exit 1
fi
echo No fixtures found
rm /tmp/test.$$

echo '*************************************************************************'
echo Building JMVC package
echo '*************************************************************************'
./js seccubus/scripts/build.js 2>&1|tee /tmp/test.$$
if [ `grep -i error /tmp/test.$$|grep -v error.ejs|wc -l` -ne 0 ]
then
	echo "Not building any further, fix your errors first"
	mv /tmp/test.$$ ../errors.txt
	less ../errors.txt
	exit 1
fi
echo "Package built"
rm /tmp/test.$$

echo '*************************************************************************'
echo Copying files
echo '*************************************************************************'
cd ..
rm -rf build/public
mkdir -p build/public/img
mkdir -p build/public/steal
mkdir -p build/public/seccubus
cp -r jmvc/seccubus/img build/public/seccubus
cp jmvc/seccubus/production.* build/public/seccubus
cp jmvc/seccubus/seccubus.html build/public/seccubus
cp jmvc/steal/steal.production.js build/public/steal

echo '*************************************************************************'
echo Patching files
echo '*************************************************************************'
mv build/public/seccubus/seccubus.html build/public/seccubus/seccubus.html.bak
sed s:steal\.js:steal.production.js: build/public/seccubus/seccubus.html.bak >build/public/seccubus/seccubus.html
rm build/public/seccubus/seccubus.html.bak
echo end
exit
