#!/bin/bash
# ------------------------------------------------------------------------------
# $Id$
# ------------------------------------------------------------------------------
# This shell script make the distribution tarball
# ------------------------------------------------------------------------------
#  Copyright 2011 Frank Breedijk of Schuberg Philis
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# ------------------------------------------------------------------------------

echo '*************************************************************************'
echo "Make sure everything is checked in"
echo '*************************************************************************'
if [ `svn status|wc -l` -ne 0 ]
then
        echo "Something isn't checked in yet"
        echo "Fix the error and rerun make_tarball"
        svn status
        exit 1
fi

echo '*************************************************************************'
echo "Lets see if our perl compiles";
echo '*************************************************************************'
./perl_ok.pl 2>&1 | tee /tmp/test.$$
if [ `grep 'nok' /tmp/test.$$ |wc -l` -gt 0 ]
then
        rm /tmp/test.$$
        exit 1
fi

echo '*************************************************************************'
echo "Building tarball"
echo '*************************************************************************'
perl Makefile.PL
make clean
perl Makefile.PL
#rm MANIFEST
make manifest
perl Makefile.PL
make
rm Seccubus-*.tar.gz
make dist

