#!/bin/bash
# ------------------------------------------------------------------------------
# This shell script runs the command to make a valid distrbution including
# making a MANIFEST
# 
# Before a distribution can be built perl files will be checked for syntaxt and
# the jmvc unit test ha
# ------------------------------------------------------------------------------


# Updated this test to Git due to issue #20
echo '*************************************************************************'
echo "Make sure everything is checked in"
echo '*************************************************************************'
if [ `git status|wc -l` -ne 2 ]
then
	echo "Something isn't checked in yet"
	git status
	exit 1
fi 

echo '*************************************************************************'
echo "Lets see if all jmvc unit tests pass"
echo '*************************************************************************'
#./unit_test_jmvc |tee /tmp/test.$$
echo OK > /tmp/test.$$
if [ `grep 'OK' /tmp/test.$$|wc -l` -lt 1 ] 
then
	rm /tmp/test.$$
	exit 1
fi 

echo '*************************************************************************'
echo "Building jmvc"
echo '*************************************************************************'
./build_jmvc |tee /tmp/test.$$
if [ `grep 'Disable fixtures first' /tmp/test.$$|wc -l` -gt 0 ]
then
	rm /tmp/test.$$
	exit 1
fi

rm /tmp/test.$$

echo '*************************************************************************'
echo "Building distribution tarball"
echo '*************************************************************************'
./make_tarball

rm /tmp/test.$$ 2>/dev/null
exit 0
