#!/bin/bash
# ------------------------------------------------------------------------------
# $Id$
# ------------------------------------------------------------------------------
# This shell script make the distribution tarball
# ------------------------------------------------------------------------------

echo '*************************************************************************'
echo "Unit testing time"
echo '*************************************************************************'
prove -v 2>&1 | tee /tmp/test.$$
if [ `grep 'not ok' /tmp/test.$$ |wc -l` -gt 0 ]
then
        rm /tmp/test.$$
        exit 1
fi

echo '*************************************************************************'
echo "Building tarball"
echo '*************************************************************************'
perl Makefile.PL
make clean
perl Makefile.PL
rm MANIFEST
make manifest
perl Makefile.PL
make
rm Seccubus-*.tar.gz
make dist

