#!/bin/bash
# ------------------------------------------------------------------------------
# $Id$
# ------------------------------------------------------------------------------
#  Copyright 2011 Frank Breedijk of Schuberg Philis
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# ------------------------------------------------------------------------------
cd jmvc

echo '*************************************************************************'
echo Checking if fixtures are disabled
echo '*************************************************************************'

cat seccubus/seccubus.js | perl -e 'while (<>) { if ( /fixtures\.js/ && ! /^\s*\/[\/\*]/ ) { print $_; } }'|tee /tmp/test.$$;

if [ `cat /tmp/test.$$|wc -l` -ne 0 ]
then
	echo "Disable fixtures first";
	rm /tmp/test.$$
	exit 1
fi
echo No fixtures found

echo '*************************************************************************'
echo Building JMVC docs
echo '*************************************************************************'
./js seccubus/scripts/docs.js

echo '*************************************************************************'
echo Building JMVC package
echo '*************************************************************************'
./js seccubus/scripts/build.js|tee /tmp/test.$$

echo '*************************************************************************'
echo Copying files
echo '*************************************************************************'
cd ..
rm -rf www/seccubus/*
cp -r jmvc/seccubus/img www/seccubus/
cp jmvc/seccubus/production.* www/seccubus/
cp jmvc/seccubus/seccubus.html www/seccubus/
cp jmvc/steal/steal.production.js www/steal

echo '*************************************************************************'
echo Patching files
echo '*************************************************************************'
mv www/seccubus/seccubus.html www/seccubus/seccubus.html.bak
sed s/steal.js/steal.production.js/ www/seccubus/seccubus.html.bak >www/seccubus/seccubus.html

echo '*************************************************************************'
echo Symlinks
echo '*************************************************************************'
if [ ! -h www/seccubus/api ]
then 
	(cd www/seccubus/;ln -s ../api)
fi
if [ ! -h www/seccubus/SeccubusV2.pm ]
then 
	(cd www/seccubus/;ln -s ../SeccubusV2.pm)
fi

echo end
