#!/usr/bin/env perl
# Copyright 2016, Glenn ten Cate (blabla1337), vagrant
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------
# This script will call the testssl.sh scanner and import the results as IVIL
# ------------------------------------------------------------------------------

use strict;
use SeccubusV2;
use SeccubusIVIL;
use SeccubusHelpers;

use Getopt::Long;
use Carp;

my (
	$testssl_path,
	$testssl_options,
	$hosts_file,
	$workspace,
	$scan,
	$nodelete,
	$remote,
	$help,
	$verbose,
	$quiet,
   );

$help = 0;
$nodelete = undef;

# Create default values

GetOptions(	
		'testssl_path|p=s'	=> \$testssl_path,
		'testssl_options|o=s'	=> \$testssl_options,
		'hosts=s'		=> \$hosts_file,
		'workspace=s'		=> \$workspace,
		'scan=s'		=> \$scan,
		'nodelete!'		=> \$nodelete,
		'remote|r=s'            => \$remote,
		'verbose|v+'		=> \$verbose,
		'quiet|q!'		=> \$quiet,
		'help|h'		=> \$help,
	  );

help() if $help;
$verbose = 0 if $quiet;

my $config = get_config();
my $load_ivil = "perl -I$config->{paths}->{modules} $config->{paths}->{bindir}\/load_ivil";
my $attach_file = "perl -I$config->{paths}->{modules} $config->{paths}->{bindir}\/attach_file";

print "Hosts file specified $hosts_file\n" if $verbose;
if ( ! $hosts_file || ! -e $hosts_file ) {
	print "You must specify a valid hosts file";
	help();
} elsif ( ! $workspace ) {
	print "You must specify a workspace name";
	help();
} elsif ( ! $scan ){
	print "You must specify a scan name";
	help();
};

$testssl_path = get_testssl_path() unless $testssl_path;
if ( ! $testssl_path && -e $testssl_path ) {
	print "Unable to find testssl on your system. I suggest you use the --testssl_path option\nto provide a path to testssl or testssl.pl\n";
	help();
}

my $tempfile = "/tmp/seccubus.$$";

my $testssl_options = "--file $hosts_file --jsonfile $tempfile.csv $testssl_options";
print "testssl options: $testssl_options\n" if $verbose;

my $timestamp = make_timestamp();
print "Timestamp = $timestamp\n" if $verbose;

print "Execuing $testssl_path $testssl_options\n" unless $quiet;
run_cmd("$testssl_path $testssl_options",$verbose,$remote,[ $tempfile,"$tempfile.*" ], [ $hosts_file ]);

print "Scanning done, converting .nbe to ivil\n" unless $quiet;
my $cmd = "perl -I$config->{paths}->{modules} $config->{paths}->{bindir}\/nbe2ivil --scanner=testssl --scannerversion=$testssl_version --workspace '$workspace' --scan '$scan' --timestamp=$timestamp --infile '$tempfile.nbe' ";
$cmd .= "-v" if $verbose > 1;
run_cmd($cmd,$verbose);

print "Importing ivil\n" unless $quiet;
$cmd = "$load_ivil --workspace '$workspace' --scan '$scan' --scanner testssl --timestamp $timestamp";
$cmd .= " -v" if $verbose > 1;
$cmd .= " '$tempfile.ivil.xml'";
run_cmd($cmd,$verbose);

print "Scan imported, adding files to scan $scan in workspace $workspace\n" unless $quiet;

$cmd = "$attach_file --workspace '$workspace' --scan '$scan' --timestamp $timestamp --file '$tempfile' --description 'Command line output'";
$cmd .= " -v" if $verbose > 1;
run_cmd($cmd,$verbose);

$cmd = "$attach_file --workspace '$workspace' --scan '$scan' --timestamp $timestamp --file '$tempfile.csv' --description 'CSV output'";
$cmd .= " -v" if $verbose > 1;
run_cmd($cmd,$verbose);

$cmd = "$attach_file --workspace '$workspace' --scan '$scan' --timestamp $timestamp --file '$tempfile.ivil.xml' --description 'IVIL output'";
$cmd .= " -v" if $verbose > 1;
run_cmd($cmd,$verbose);

# Cleanup
unless ( $nodelete ) {
	unlink "$tempfile" if -e "$tempfile";
	unlink "$tempfile.csv" if -e "$tempfile.csv";
	unlink "$tempfile.ivil.xml" if -e "$tempfile.ivil.xml";
}
if ( $remote ) {
	run_cmd("rm -f $tempfile $tempfile.*",$verbose,$remote);
}

exit(0);

sub help() {
	print "

Usage: scan 	[--testssl_path|p <path to testssl>] \\
		[--testssl_options '<additional testssl options>'] \\
		--hosts <hosts file> [--remote|r <host>,<user>,<key>] [--verbose|v] [--quiet|q]
		[--help|h]

Arguments:
--testssl_path	- You can use this optional parameter to provide the script with
(-p)		  the path to testssl.sh directory. If you do not provide this the 
		  script tries to find the files itself and fails if it cannot 
		  find it.
--testssl_options	- Additional command line options to provide to testssl see 
(-o)		  'testssl.sh --help' for more information. Please quote the options so that they are
		  passed to testssl as a single block. E.g. -o '--beast --client-simulation'
--hosts		- The file containing the 'hosts' to scan
--workspace	- Name of the workspace to load the findings into
--scan		- Name of the scan to load the findings into
--remote (-r)	- Comma separated list of hostname, username and key used to ssh into the host
		  specified and run the command
--verbose (-v)	- Be verbose during execution
--nodelete	- Don't delete temporary files
--quiet (-q)	- Don't print output
--help (-h)	- Print this message
";
	exit(1);
}

sub get_testssl_path() {
	$path = run_cmd("ls /opt/testssl.sh/testssl.sh",0,$remote);
	if ( $path == '/opt/testssl.sh/testssl.sh' ) {
		return '/opt/testssl.sh/testssl.sh';
	}
	return undef;
}

sub make_timestamp() {
	my ($second, $minute, $hour, $day, $month, $year) = localtime();
	$month++;
	$second = "0" . $second if $second < 10;
	$minute = "0" . $minute if $minute <10;
	$hour = "0". $hour if $hour < 10;
	$day = "0". $day if $day <10;
	$month = "0" . $month if $month <10;
	$year += 1900;

	return "$year$month$day$hour$minute$second";
}

