#!/usr/bin/env perl
# ------------------------------------------------------------------------------
# $Id$
# ------------------------------------------------------------------------------
# This script will call the Nmap scanner and import the results as IVIL
# ------------------------------------------------------------------------------
#  Copyright 2011 Frank Breedijk of Schuberg Philis
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# ------------------------------------------------------------------------------

use strict;
use SeccubusV2;
use SeccubusIVIL;

use Getopt::Long;
use Carp;

my (
	$nmap_path,
	$nmap_options,
	$hosts_file,
	$workspace,
	$scan,
	$sudo,
	$help,
	$verbose,
	$quiet,
	$username,
   );

$help = 0;

# Create default values

GetOptions(	
		'nmap_path|p=s'		=> \$nmap_path,
		'nmap_options|o=s'	=> \$nmap_options,
		'hosts=s'		=> \$hosts_file,
		'workspace=s'		=> \$workspace,
		'scan=s'		=> \$scan,
		'sudo'			=> \$sudo,
		'verbose|v+'		=> \$verbose,
		'quiet|q!'		=> \$quiet,
		'help|h'		=> \$help,
	  );

help() if $help;
$verbose = 0 if $quiet;

my $config = get_config();

print "Hosts file specified $hosts_file\n" if $verbose;
if ( ! $hosts_file || ! -e $hosts_file ) {
	print "You must specify a valid hosts file";
	help();
} elsif ( ! $workspace ) {
	print "You must specify a workspace name";
	help();
} elsif ( ! $scan ){
	print "You must specify a scan name";
	help();
};

$nmap_path = get_nmap_path() unless $nmap_path;
if ( ! $nmap_path && -e $nmap_path ) {
	print "Unable to find Nmap on you system. I suggest you use the --nmap_path option\nto provide a path to the nmap executable\n";
	help();
}
print "Nmap found in $nmap_path\n" if $verbose;
my $nmap_version = get_nmap_version($nmap_path);

my $tempfile = "/tmp/seccubus.$$";

my $nmap_options = "-iL $hosts_file -oA $tempfile $nmap_options";
print "Nmap options: $nmap_options\n" if $verbose;

my $timestamp = make_timestamp();
print "Timestamp = $timestamp\n" if $verbose;
my $load_ivil = "perl -I$config->{paths}->{modules} $config->{paths}->{bindir}\/load_ivil";

my $cmd = "$nmap_path $nmap_options";
if ( $sudo ) {
	print "Sudo mode on\n" if $verbose;
	$cmd = "sudo $cmd";
}
if ( $sudo ) {
	$username = `whoami`;
	chomp($username);
}

print "Execuing $cmd\n" unless $quiet;
open NMAP, "$cmd |" or die "Unable to open pipe";

while ( <NMAP> ) {
	print $_ if $verbose;
}
close NMAP;

if ( $sudo ) {
	$cmd = "chown $username $tempfile\.*";

	print "Execuing $cmd\n" unless $quiet;
	open NMAP, "$cmd |" or die "Unable to open pipe";

	while ( <NMAP> ) {
		print $_ if $verbose;
	}
	close NMAP;
}


print "Scanning done, converting .xml to ivil\n" unless $quiet;
$cmd = "perl -I$config->{paths}->{modules} $config->{paths}->{bindir}\/nmap2ivil --scannerversion=$nmap_version --workspace=$workspace --scan=$scan --timestamp=$timestamp --infile=$tempfile.xml ";
$cmd .= "-v" if $verbose > 1;

print "Executing $cmd\n" if $verbose;
my $result = `$cmd 2>&1`;
print "$result\n" if $verbose;

print "Importing ivil\n" unless $quiet;
$cmd = "$load_ivil --workspace $workspace --scan $scan --scanner Nmap --scannerversion $nmap_version --timestamp $timestamp";
$cmd .= " -v" if $verbose > 1;
$cmd .= " $tempfile.ivil.xml";
print "Execuing $cmd\n" if $verbose > 1;
my $result = `$cmd 2>&1`;
print "$result\n" if $verbose > 1;

#print "Scan imported, adding files to scan $scan in workspace $workspace\n" unless $quiet;
# TODO: Add files to scan
#add_file_to_scan($workspace, $scan, $timestamp, "$tempfile.nmap", "Command output");
#add_file_to_scan($workspace, $scan, $timestamp, "$tempfile.gnmap", "Nmap greppable format");
#add_file_to_scan($workspace, $scan, $timestamp, "$tempfile.xml", "Nmap xml output");
#add_file_to_scan($workspace, $scan, $timestamp, "$tempfile.ivil.nbe", "IVIL output");

# Cleanup
unlink "$tempfile.gnmap" if -e "$tempfile.gnmap";
unlink "$tempfile.nmap" if -e "$tempfile.nmap";
unlink "$tempfile.xml" if -e "$tempfile.xml";
unlink "$tempfile.ivil.xml" if -e "$tempfile.ivil.xml";

exit(0);

sub help() {
	print "
Usage: scan 	[--nmap_path|p <path to nmap>] \\
		[--nmap_options <additional Nmap options>]] \\
		--hosts <hosts file> [--verbose|v] [--quiet|q] [--help|h]

Arguments:
--nmap_path	- You can use this optional parameter to provide the script with
(-p)		  the path to nmap. If you do not provide this the 
		  script tries to find the files itself and fail if it cannot 
		  fidn them.
--nmap_options	- Additional command line options to provide to Nmap see 
(-o)		  'nmap -Help' for more information.
--hosts		- The file containing the 'hosts' to scan
--workspace	- Name of the workspace to load the findings into
--scan		- Name of the scan to load the findings into
--verbose (-v)	- Be verbose during execution
--quiet (-q)	- Don't print output
--help (-h)	- Print this message
";
	exit(1);
}

sub get_nmap_path() {
	my $path = `which nmap`;
	if ( $path =~ /(^\/.*nmap)/ ) {
		return $1;
	}
	$path = `which nmap.pl`;
	if ( $path =~ /(^\/.*nmap\.pl)/ ) {
		return $1;
	}
	if ( -e '/opt/nmap/nmap.pl' ) {
		return '/opt/nmap/nmap.pl';
	}
	return undef;
}

sub get_nmap_version() {
	my $nmap_path = shift;

	my $version=`$nmap_path -V`;
	$version =~ /Nmap version\s+(\d+\.\d+)/;
	return $1;
}

sub make_timestamp() {
	my ($second, $minute, $hour, $day, $month, $year) = localtime();
	$month++;
	$second = "0" . $second if $second < 10;
	$minute = "0" . $minute if $minute <10;
	$hour = "0". $hour if $hour < 10;
	$day = "0". $day if $day <10;
	$month = "0" . $month if $month <10;
	$year += 1900;

	return "$year$month$day$hour$minute$second";
}

