#!/bin/bash
# Copyright 2015 Frank Breedijk
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
VER=8
DB="mysql"
if [ "$DB" == "mysql" ] 
then
	echo "mysqladmin -u root drop seccubus"
	mysqladmin -u root drop seccubus
	echo "mysqladmin -u root create seccubus"
	mysqladmin -u root create seccubus
	echo "mysql -u root seccubus < structure_v$VER.mysql"
	mysql -u root seccubus < db/structure_v$VER.mysql
	echo "mysql -u root seccubus < data_v$VER.mysql"
	mysql -u root seccubus < db/data_v$VER.mysql
fi
