#!/bin/bash
# Copyright 2014 Frank Breedijk, Petr
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
VER=6
DB="mysql"
if [ "$DB" == "mysql" ] 
then
	echo "mysqladmin -p drop Seccubus"
	mysqladmin -p drop Seccubus
	echo "mysqladmin -p create Seccubus"
	mysqladmin -p create Seccubus
	echo "mysql -p Seccubus < structure_v$VER.mysql"
	mysql -p Seccubus < structure_v$VER.mysql
	echo "mysql -p Seccubus < data_v$VER.mysql"
	mysql -p Seccubus < data_v$VER.mysql
fi
