#!/usr/bin/env perl
# Copyright 2013 Frank Breedijk
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------
# This perl  updates the safe and full nessus-rc files with the latest
# plugins downloaded by nessus
# ------------------------------------------------------------------------------

use strict;
use SeccubusV2;
use SeccubusIVIL;

use Getopt::Long;
use Carp;

my $config = get_config();
my $dir = "$config->{paths}->{scanners}/NessusLegacy";

if ( ! -e "$dir/.update-nessusrc" ) {
	help();
}

my (
	$verbose,
	$quiet,
   );

GetOptions(
		'verbose|v+'	=> \$verbose,
		'quiet|q!'	=> \$quiet,
	  );

$verbose = 0 if $quiet;

print "Updating safe.nessusrc\n" if $verbose;
my $cmd = "(cd $dir;./update-nessusrc -i \"10180,10335,14274,14260\" -x \"10796,11219,11840,14272,14259\" $config->{paths}->{configdir}/safe.nessusrc)";
print "Execuing $cmd\n" unless $quiet;
my $result = `$cmd 2>&1`;
print "$result\n" if $verbose;
print "Done\n" if $verbose;

print "Updating full.nessusrc\n" if $verbose;
$cmd = "( cd $dir;./update-nessusrc -c \"_all_\" -c \"!scanners\" -i \"10180,10335,14274,14260\" -x \"10796,11219,11840,14259,14272\" $config->{paths}->{configdir}/safe.nessusrc)";
print "Execuing $cmd\n" unless $quiet;
$result = `$cmd 2>&1`;
print "$result\n" if $verbose;
print "Done\n" if $verbose;

sub help() {
        print "
Usage: update-rcs [--verbose|-v] [--quiet|-q]

When called this script will call update-nessusrc written by George A. Theall 
(theall\@tifaware.com) multiple times to update the two .nessusrc distributed 
with Seccubus V2.

You are expected to modify this script yourself if you use more .nessusrc files
your are expected to keep then up-to-date yourself or to edit thsi script to include them.

This script expects a .update-nessusrc file to be present in 
<ScannerDir>/NessusLegacy. <ScannerDIr> is specified in your Seccubus config.xml
file (currently set to '$config->{paths}->{scanners}')

If you do not have it, you can use (dot)update-nessusrc.example to create it and
then rename it to .update-nessusrc
	";
	exit(1);
}
